<a href="https://colab.research.google.com/github/seismomat/NumericoMio/blob/master/CancelacionNumerica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Cancelación numérica</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M.en.C.Miguel Ángel Pérez León</i></h5>
    <h5 align="center"><i>Ayudante: Jesús Iván Coss Calderón</i></h5>
    <h5 align="center"><i>Materia: Análisis numérico</i></h5>
  </font>

**Objetivo general**

* Entender cómo funciona la cancelación numérica en los lenguajes de programación.

**Objetivos particulares**

* Observar la cancelación numérica con la fórmula general de segundo grado.
* Observar la cancelación numérica al calcular el límite de una función.

<a name='c1'></a>

## Contenido

- [Introducción](#1)
    - [Bibliotecas a utilizar](#1-1)
- [Fórmula general de segundo grado](#2)
    - [Programa sin radicalización.](#2-1)
    - [Fundamento](#2-2)
    - [Programa con radicalización](#2-3)
    - [Fundamento](#2-4)    
- [Límite de una función.](#3)
    - [Programa 1.](#3-1)
    - [Programa 2.](#3-2)

<a name='1'></a>

# Introducción 

En el mundo del análisis numérico, no sólo tenemos que tener cuidado con aplicar la matemática de manera correcta, sino también saber como los efectos de redondeo y truncamiento pueden afectar nuestras aproximaciones. Ya que, puede ser que tengamos cancelaciones debido a que algún factor que se está haciendo cada vez más pequeño, por lo que se deben buscar estrategias para modificar nuestros cálculos y que las aproximaciones sean factibles.

<a name='1-1'></a>

## Bibliotecas a utilizar

In [16]:
import import_ipynb
import numpy as np
import Tools_cancelation as Tc

<a name='2'></a>

# Fórmula general de segundo grado

[regresar al contenido](#c1) 

Las ecuaciones de segundo grado pueden ser resueltas con la ayuda de la llamada fórmula general de segundo grado, que tiene la siguiente forma 

$$ ax^{2} + bx +c =0, $$

donde $a,b,c \in \Bbb R$.

Vamos a tomar como ejemplo el siguiente polinomio de segundo orden, y obtener sus raíces.

$$ x^{2} - (10^{10} +10^{-10})x +1 =0. $$

¿Qué resultado se obtiene?, ¿se presenta cancelación numérica?,¿por qué sucede la cancelación numérica?.

<a name='2-1'></a>

## Programa sin radicalización.

[regresar al contenido](#c1)

In [17]:
## se declaran los coeficientes de la ecuación ax ^2 + bx + c 
a= 1.0; # coeficiente ax ^2 
b= -(1E11 + 1E-10); # coeficiente bx
c=1.0; # coeficiente c

In [18]:
def SinRad(a,b,c):
    """
    Calcula la Chicharronera sin radicalización 
    para una ecuación del tipo 
                    ax ^2 + bx + c
    
    Parámetros
    -----------
    a: float
        entrada, coeficiente a
    b: float
        entrada, coeficiente b
    c: float
        entrada, coeficiente c
    
    Regreso
    ----------
    X1: float
        primera raíz
    
    X2: float
        segunda raíz
    """
    
    discri= np.sqrt(b**2 - 4*a*c)
    
    X1=(-b + discri)/(2.0*a)
    X2=(-b - discri)/(2.0*a)
    
    return [X1],[X2]

In [19]:
X1,X2=SinRad(a,b,c)
Tc.printing("X1","X2",X1,X2)

             X1   X2
0  1.000000e+11  0.0

<a name='2-2'></a>

## Fundamento

[regresar al contenido](#c1)

Debido al sistema de punto flotante, se tiene el siguiente redondeo

$$ b= - 10^{10} - 10^{-10} \approx  - 10^{10}$$

mientras que en el discriminante se obtiene

$$ \sqrt{(10^{10}) ^{2} - 4* 1*1 } \approx  10^{10} $$

por lo que, para el cálculo de la raíz 

$$ x_{2} = \frac{10^{10} -  \sqrt{(10^{10}) ^{2} - 4* 1*1 }}{2} $$

$$ x_{2} = \frac{10^{10} -10^{10}}{2} $$

$$ x_{2} = 0 $$

por otro lado,

$$ \sqrt{(10^{10}) ^{2} - 4* 1*1 } \approx  10^{10} $$

por lo que, para el cálculo de la raíz 

$$ x_{1} = \frac{10^{10} +  \sqrt{(10^{10}) ^{2} - 4* 1*1 }}{2} $$

$$ x_{1} = \frac{10^{10} +10^{10}}{2} $$

$$ x_{1} = 10^{10} $$

<a name='2-3'></a>

## Programa con radicalización.

[regresar al contenido](#c1)

In [20]:
def ConRad(a,b,c):
    """
    Calcula la Chicharronera con radicalización 
    para una ecuación del tipo 
                    ax ^2 + bx + c
    
    Parámetros
    -----------
    a: float
        entrada, coeficiente a
    b: float
        entrada, coeficiente b
    c: float
        entrada, coeficiente c
    
    Regreso
    ----------
    X1: float
        primera raíz
    
    X2: float
        segunda raíz
    """
    
    discri= np.sqrt(b**2 - 4*a*c)
    
    X2=(2*c)/(-b+discri)
    X1=(-b + discri)/(2.0*a)
    
    return [X1],[X2]

In [21]:
X1_r,X2_r=ConRad(a,b,c)
Tc.printing("X1","X2",X1_r,X2_r)

             X1            X2
0  1.000000e+11  1.000000e-11

In [22]:
Tc.printing("X1","X2",[X1,X1_r],[X2,X2_r])

                 X1       X2
0  [100000000000.0]    [0.0]
1  [100000000000.0]  [1e-11]

<a name='2-4'></a>

## Fundamento

[regresar al contenido](#c1) 

Para resolver el problema de la cancelación numérica, se debe radicalizar, el discriminante de la fórmula de segundo grado

$$ x_{2} = \frac{-b +  \sqrt{b^{2}-4ac}}{2a}  $$

Multiplicando por un uno de manera convenientey sabemos que $b<0$, entonces tenemos que 


$$ x_{2} = \frac{b -  \sqrt{b^{2}-4ac}}{2a} \Bigg( \frac{b +  \sqrt{b^{2}-4ac}}{b + \sqrt{b^{2}-4ac}}\Bigg)  $$


$$ x_{2} = \frac{2c}{b +  \sqrt{b^{2}-4ac}} \approx \frac{c}{b}$$

<a name='3'></a>

# Límite de una función.

[regresar al contenido](#c1) 

Considera la función

$$f(x) = \frac{(e^x-1)}{x}$$

Usa la regla de l'Hopital para probar que 

$$\underset{x \rightarrow 0}{\lim} f(x) = 1$$

Probando

$$\begin{equation*} 
\begin{split}
\underset{x \rightarrow 0}{\lim} \frac{e^x-1}{x}\\
\underset{x \rightarrow 0}{\lim} \frac{ \frac{d}{dx} ( e^x-1)}{ \frac{d}{dx} x} \\
\underset{x \rightarrow 0}{\lim} \frac{ e^x}{ 1} \\
\underset{x \rightarrow 0}{\lim} e^x =1
\end{split}
\end{equation*}$$

<a name='3-1'></a>

## Programa 1.

[regresar al contenido](#c1)

In [37]:
def lim1(k):
    """
    Calcula el limite de la función 
                    exp(x)-1 / x
    
    Parámetros
    -----------
    k: int
        entrada
   
    Regreso
    ----------
    xs: list
        lista con los valores de x
    
    lim_f_x: list
        lista con los valores del limite
    """
    ks=np.arange(1,k+1)
    lim_f_x=[];xs=[]
    for k in ks:
        x=1/(10**(k))
        xs.append(x)
        lim_f_x.append((np.exp(x)-1)/x)
        
    return xs,lim_f_x

In [38]:
x,lim_fx=lim1(20)
Tc.printing("Xs","lim_fx",x,lim_fx)

              Xs    lim_fx
0   1.000000e-01  1.051709
1   1.000000e-02  1.005017
2   1.000000e-03  1.000500
3   1.000000e-04  1.000050
4   1.000000e-05  1.000005
5   1.000000e-06  1.000000
6   1.000000e-07  1.000000
7   1.000000e-08  1.000000
8   1.000000e-09  1.000000
9   7.091870e-10  1.000000
10  8.225360e-10  1.000000
11 -1.374797e-09  1.000000
12  7.598005e-10  1.000000
13  3.617327e-09  1.000000
14 -6.533834e-10  1.000000
15  5.333563e-10  1.000000
16  6.372166e-10  1.000000
17 -6.726675e-10  1.000000
18 -5.047231e-10  1.000000
19  6.016873e-10  1.000000

<a name='3-2'></a>

## Programa 2.

[regresar al contenido](#c1)

In [25]:
def lim2(k):
    """
    Calcula el limite de la función 
                    exp(x)-1 / ln(exp(x))
    
    Parámetros
    -----------
    k: int
        entrada
   
    Regreso
    ----------
    xs: list
        lista con los valores de x
    
    lim_f_x: list
        lista con los valores del limite
    """
    ks=np.arange(1,k+1)
    lim_f_x=[];xs=[]
    for k in ks:
        x=1/(10**(k))
        xs.append(x)
        lim_f_x.append((np.exp(x)-1)/( np.log(np.exp(x) )))
        
    return xs,lim_f_x

In [26]:
x,lim_fx=lim2(30)
Tc.printing("Xs","lim_fx",x,lim_fx)

              Xs    lim_fx
0   1.000000e-01  1.051709
1   1.000000e-02  1.005017
2   1.000000e-03  1.000500
3   1.000000e-04  1.000050
4   1.000000e-05  1.000005
5   1.000000e-06  1.000001
6   1.000000e-07  1.000000
7   1.000000e-08  1.000000
8   1.000000e-09  1.000000
9   7.091870e-10  1.000000
10  8.225360e-10  1.000000
11 -1.374797e-09  1.000000
12  7.598005e-10  1.000000
13  3.617327e-09  1.000000
14 -6.533834e-10  1.000000
15  5.333563e-10  1.000000
16  6.372166e-10  1.000000
17 -6.726675e-10  1.000000
18 -5.047231e-10  1.000000
19  6.016873e-10  1.000000
20 -1.785907e-09  1.000000
21 -7.666192e-10  1.000000
22 -6.274173e-09  1.000000
23 -6.274173e-10  1.000000
24  8.054682e-10  1.000000
25 -2.128737e-09  1.000000
26 -2.483527e-09  1.000000
27  3.725290e-09  1.000000
28 -6.208817e-10  1.000000
29  9.313226e-10  1.000000

In [27]:
x=1
der_anal=np.cos(x)
f=lambda x:np.sin(x)
der_anal

0.5403023058681398

In [28]:
def derivation(f,x):
    """
    derivation(f,x)

    This function computes the derivative of a function f at a point x.

    Parameters
    ----------
    f : function
        The function whose derivative is to be computed.
    x : float
        The point at which the derivative is to be computed.

    Returns
    -------
    hs : list
        A list of the values of h used in the computation.
    der : list
        A list of the derivatives computed for each value of h.
    """
    der=[];hs=[];n=20
    for i in range(n):
        h=0.0;deri=0.0;
        h=10**(-i);
        deri=(f(x+h)-f(x))/h;
        der.append(deri);
        hs.append(h);
    return hs,der

In [29]:
hs,der=derivation(f,x)
Tc.printing("h","Valor de la derivada",hs,der)

               h  Valor de la derivada
0   1.000000e+00              0.067826
1   1.000000e-01              0.497364
2   1.000000e-02              0.536086
3   1.000000e-03              0.539881
4   1.000000e-04              0.540260
5   1.000000e-05              0.540298
6   1.000000e-06              0.540302
7   1.000000e-07              0.540302
8   1.000000e-08              0.540302
9   1.000000e-09              0.540302
10  1.000000e-10              0.540302
11  1.000000e-11              0.540301
12  1.000000e-12              0.540346
13  1.000000e-13              0.539568
14  1.000000e-14              0.544009
15  1.000000e-15              0.555112
16  1.000000e-16              0.000000
17  1.000000e-17              0.000000
18  1.000000e-18              0.000000
19  1.000000e-19              0.000000

In [30]:
def derivation1(f,x):
    der=[];hs=[];n=20
    for i in range(n):
        h=0.0;deri=0.0;
        h=10**(-i);
        deri=(f(x+h)-f(x-h))/(2*h);
        der.append(deri);
        hs.append(h);
    return hs,der

hs,der=derivation1(f,x)
Tc.printing("h","Valor de la derivada",hs,der)

               h  Valor de la derivada
0   1.000000e+00              0.454649
1   1.000000e-01              0.539402
2   1.000000e-02              0.540293
3   1.000000e-03              0.540302
4   1.000000e-04              0.540302
5   1.000000e-05              0.540302
6   1.000000e-06              0.540302
7   1.000000e-07              0.540302
8   1.000000e-08              0.540302
9   1.000000e-09              0.540302
10  1.000000e-10              0.540302
11  1.000000e-11              0.540301
12  1.000000e-12              0.540290
13  1.000000e-13              0.540124
14  1.000000e-14              0.544009
15  1.000000e-15              0.555112
16  1.000000e-16              0.555112
17  1.000000e-17              0.000000
18  1.000000e-18              0.000000
19  1.000000e-19              0.000000